<a href="https://colab.research.google.com/github/Papijohan000/johan-machine-learning/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [1]:
# Import numpy as np and see the version
import numpy as np
# your code here
pass

In [2]:
# Create a 1D array of numbers from 0 to 9
# your code here
pass
array = list (range(10))
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
pass
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print(random_vector)

[0.58999924 0.42174902 0.60198277 0.55539472 0.29551497 0.15818328
 0.31536989 0.64432628 0.         0.1455748 ]


In [4]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
pass
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
number_8 = arr[1, 2]
print(number_8)

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7])
subset = arr[2:5]
print(subset)

[3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7])
last_4_numbers = arr[-4:]
print(last_4_numbers)

[4 5 6 7]


In [10]:
# Create a 3×3 numpy array of all True’s
# your code here
pass
true_array = np.ones((3, 3), dtype=bool)
print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
# Extract all odd numbers from arr
# your code here
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]
print( odd_numbers)


[1 3 5 7 9]


In [13]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
pass
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# Reverse a vector (first element becomes last)
pass
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print( vector)
print(reversed_vector)

[1 2 3 4 5]
[5 4 3 2 1]


In [15]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
pass
min_value = 1
max_value = 100
random_array = np.random.randint(min_value, max_value, size=(10, 10))
minimum_value = np.min(random_array)
maximum_value = np.max(random_array)
print(random_array)
print( minimum_value)
print( maximum_value)

[[37 54 65 13 40 85 10 33 53 61]
 [ 3  8 93 95 31 96 63 71 11 69]
 [24 63 47 26 48 94 32 89 30  9]
 [20 57 40 82 95 33 79 49 34 20]
 [66 55 54 21 67 94 63  1 98 60]
 [59 91 88 90  3 76 23  4 45  4]
 [55  9 46 15 95 72 81 57 15 45]
 [76 88 50 31 39 23  7 32 59  2]
 [42 60 94 64 29 52 75 24 65 93]
 [88 56 41 51 73  7 15 26 49 12]]
1
98


In [17]:
# Create a 3x3x3 array with random values
pass
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.72413634 0.39167499 0.02193588]
  [0.44332661 0.84556528 0.74943622]
  [0.11779252 0.27566047 0.30430923]]

 [[0.40977211 0.01899729 0.80270709]
  [0.79930232 0.11609956 0.30508029]
  [0.76469958 0.22514317 0.05050982]]

 [[0.96628332 0.53011608 0.05227346]
  [0.07409726 0.70181959 0.28541422]
  [0.92814232 0.7934397  0.91457132]]]


In [18]:
# Replace all odd numbers in arr with -1
# your code here
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [19]:
# Create an array of type float
pass
float_array = np.array([1.0, 2.5, 3.7, 4.2], dtype=float)
print(float_array)


[1.  2.5 3.7 4.2]


In [20]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
pass
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_2d_array = original_array.reshape(2, -1)
print(original_array)
print(new_2d_array)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
pass
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print( Z1)
print( Z2)


[8 1 8 9 1 6 0 7 8 6]
[9 3 4 0 5 6 3 3 0 0]


In [23]:
#  Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
are_equal = np.array_equal(A, B)
if are_equal:
    print(A)
else:
    print(B)

pass

[1 0 1 1 1]


In [24]:
# Stack arrays a and b vertically
# your code here
pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_arrays = np.vstack((a, b))
print(stacked_arrays)

[[1 2 3]
 [4 5 6]]


In [25]:
# Stack the arrays a and b horizontally.
# your code here
pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arrays = np.hstack((a, b))
print(stacked_arrays)

[1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
# pass
tmp = np.array([2, 4, 6, 8, 10, 12, 14, 16])
items_between_5_and_10 = tmp[(tmp >= 5) & (tmp <= 10)]

In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)


5

In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]